### ISSUE TITLE
Écrire en français

### ISSUE THREAD

**Issue by taokann** [ModernChocolate/ynotes#1]
Ben ouais, Écoledirecte et Pronote ne sont disponibles qu'en France, tous les utilisateurs de l'app parlent donc la langue de Molière. Évidemment je parle juste du readme et autre documentations, surtout pas les messages de commit et encore moins le code xD
D'ailleurs je me demande quelles apps utilisent les étudiants d'autres pays...

**Comment by ModernChocolate** [comment]
Bien vu, automatisme 😂 je traduis dès que je peux
