### ISSUE TITLE
La version pour Pronote n'affiche pas mes notes

### ISSUE THREAD

**Issue by Max1Truc** [ModernChocolate/ynotes#18]
Mon établissement utilise Pronote avec l'ENT ile de france.
Je ne peux pas accéder à mes notes depuis l'appli.
C'est probablement lié au fait que mon établissement fonctionne par semestres au lieu de trimestres...
![Screenshot_20210320-115718](https://user-images.githubusercontent.com/26603929/111867443-431b3400-8974-11eb-82d3-e3eed8024033.png)

**Comment by ModernChocolate** [comment]
Bonjour, ce n'est certainement pas lié à cela. yNotes sait totalement afficher les semestres aussi bien que les trimestres. C'est probablement lié à une valeur qui ne devrait pas être nulle, c'est un problème récurrent lors de l'ajout de nouvelles fonctionnalités mais difficile à déboguer. 
Avez vous : 

- [ ] Redémarré l'application 
- [ ] Rechargé la page

**Comment by Max1Truc** [comment]
Oui j'ai fait les deux

**Comment by Max1Truc** [comment]
Le bug est corrigé, je ferme l'issue
