### ISSUE TITLE
Avoir la moyenne de la classe de l'enseignement de spécialité

### ISSUE THREAD

**Issue by florian-lefebvre** [ModernChocolate/ynotes#2]
Bonsoir,
tout d'abord super appli ! Je trouve ça très intéressant et je compte bien vous donner un coup de main si j'ai le temps.
Voici ma requête (j'utilise EcoleDirecte) : 
Avec la réforme du bac, il y a maintenant les enseignements de spécialité, ce qui veut dire que les moyennes des EDS ne sont pas réelles. Est-ce qu'il n'y aurait pas moyen d'afficher en plus la moyenne de la classe de l'EDS ? Je ne sais même pas si EcoleDirecte gère ce système là.

EDIT: est-ce que ça sert à ça le Tri dans la section notes ?

**Comment by ModernChocolate** [comment]
> EDIT: est-ce que ça sert à ça le Tri dans la section notes ?

Bonsoir, effectivement le bouton Tri permet d'afficher une moyenne par sélection de matières. Les spécialités peuvent être renseignées dans les paramètres. Il est cependant impossible d'afficher la moyenne de classe de spécialités tout simplement comme vous l'avez précisé car EcoleDirecte et Pronote n'envoient pas ces informations.

Cela me serait très agréable de travailler avec de nouvelles personnes ! Je vous invite à rejoindre le serveur Discord pour me contacter : @https://discord.gg/Au5qEx
