### ISSUE TITLE
Paramètres

### ISSUE THREAD

**Issue by florian-lefebvre** [ModernChocolate/ynotes#3]
Je pense que les paramètres devraient être accessible de partout (peut-être dans la barre en bas ?), ce n'est pas très intuitif d'avoir les paramètres globaux dans Space.

**Comment by ModernChocolate** [comment]
> Je pense que les paramètres devraient être accessible de partout (peut-être dans la barre en bas ?), ce n'est pas très intuitif d'avoir les paramètres globaux dans Space.

Bonjour, merci de vos retours ! 
Initialement les paramètres étaient (uniquement d'ailleurs) accessibles par un overlay apparaissant par un appui long sur le bouton de navigation Space. Cet overlay devrait être rajouté et amélioré au cours des versions 0.9 à 1.0.

**Comment by ModernChocolate** [comment]
Les paramètres étant désormais accessibles depuis le nouveau drawer je ferme cette issue.
