### ISSUE TITLE
Ergonomie

### ISSUE THREAD

**Issue by florian-lefebvre** [ModernChocolate/ynotes#4]
Je pense que la dernière note a une place trop importante, on ne voit pas assez ce qu'il y a à faire. Ce serait peut-être plus judicieux de mettre côte à côte en haut le travail fait et cette note pour laisser tout le reste de l'écran pour les devoirs. D'ailleurs, ce serait bien d'avoir une information sur le nombre de contrôles à venir.

**Comment by ModernChocolate** [comment]
> Je pense que la dernière note a une place trop importante, on ne voit pas assez ce qu'il y a à faire. Ce serait peut-être plus judicieux de mettre côte à côte en haut le travail fait et cette note pour laisser tout le reste de l'écran pour les devoirs. D'ailleurs, ce serait bien d'avoir une information sur le nombre de contrôles à venir.

Bonsoir, votre commentaire démontre le manque d'ergonomie de la partie Notes du menu de résumé qui est en fait un slider montrant non pas seulement la dernière note mais **plusieurs notes** en le faisant défiler vers la droite. 

Le nombre de contrôles à venir sera affiché en plus de nombreuses autres informations "statistiques" au cours de l'intégration de Space (je vous invite à lire la section décrivant ce projet dans le readme).
