### ISSUE TITLE
Content-type : faute de frappe

### ISSUE THREAD

**Issue by florian-lefebvre** [ModernChocolate/ynotes#5]
Dans /lib/parsers/EcoleDirecte.dart, il y a une erreur ligne 76
`Map<String, String> headers = {"Content-type": "texet/plain"};`

**Comment by ModernChocolate** [comment]
> Dans /lib/parsers/EcoleDirecte.dart, il y a une erreur ligne 76
> `Map<String, String> headers = {"Content-type": "texet/plain"};`

Merci pour le retour, ce problème sera corrigé dans une minor à venir.
